timezone: Australia/Canberra
name: Paul Warren
shortname: pwarren
description: "An Internaught"
github_repo: https://github.com/pwarren/pwarren.github.io
avatar: grr_square.jpg
copyright: 2014 Paul Warren

# Site URL
url: https://blog.pwarren.id.au

# Comment out if not wanted, change if wanted.
twitter: https://twitter.com/pawarren
facebook: https://facebook.com/p.a.warren
googleplus: https://plus.google.com/+PaulWarren0
github: https://github.com/pwarren
gittip: https://gittip.com/pwarren
#flickr: https://flickr.com/photos/pfenwick

# Flattr username
flattr: pwarren

paginate: 10

scholar:
    style: ieee

exclude: 
    - '_assets'
    - 'bin'
    - 'CNAME'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'Rakefile.rb'
    - 'README.md'

search:
    google:
        cx: '012331078847810483329:n0m96tpdc2s'

#addthis:
#  publisher: ra-52daa5464f2c1c4b

analytics:
  id: UA-47603317-1

disqus:
  shortname: aloeblog

sidebar:
  - tech:
    title: "Technology"
    url: "/tag/tech"
  - radio:
    title: "Radio"
    url: "/tag/radio"
  - coffee:
    title: "Coffee"
    url: "/tag/coffee"

sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/feed.xml"
