timezone: Australia/Canberra
name: Paul Warren
shortname: pwarren
description: "A geek of various shades"
github_repo: https://github.com/pwarren/pjf.github.io
avatar: grr_square.jpg
copyright: 2014 Paul Warren

# Site URL
url: http://pwarren.id.au

# Comment out if not wanted, change if wanted.
twitter: https://twitter.com/pawarren
facebook: https://facebook.com/p.a.warren
googleplus: https://plus.google.com/+PaulWarren0
github: https://github.com/pwarren
gittip: https://gittip.com/pwarren
#flickr: https://flickr.com/photos/pfenwick

# Flattr username
flattr: pwarren

paginate: 5

scholar:
    style: ieee

exclude: 
    - '_assets'
    - 'bin'
    - 'CNAME'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'Rakefile.rb'
    - 'README.md'

search:
    google:
        cx: 'partner-pub-5040518412301671:2427815553'

#addthis:
#  publisher: ra-52daa5464f2c1c4b

analytics:
  id: UA-27161555-1

disqus:
  shortname: pwarren

sidebar:
  - talks:
    title: "Talks"
    url: "/talks"
  - tech:
    title: "Technology"
    url: "/tech"
  - family:
    title: "Family Stories"
    url: "/family"
  - recipes:
    title: "Recipes"
    url: "/recipes"

sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/feed.xml"
